CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR UNIQUE NOT NULL,
  "password" VARCHAR NOT NULL,
  "full_name" VARCHAR,
  "role" VARCHAR NOT NULL,
  "created_at" TIMESTAMP
);

CREATE TABLE "department" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL
);

CREATE TABLE "department_members" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR NOT NULL,
  "department_id" BIGINT
);

CREATE TABLE "polls" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR NOT NULL,
  "description" VARCHAR(1000) NOT NULL,
  "question" VARCHAR NOT NULL,
  "creator_id" BIGINT,
  "multi_select" BOOLEAN,
  "expires_at" TIMESTAMP,
  "active" BOOLEAN DEFAULT true,
  "created_at" TIMESTAMP
);

CREATE TABLE "poll_options" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "poll_id" BIGINT,
  "option_text" VARCHAR NOT NULL,
  "vote_count" INT DEFAULT 0
);

CREATE TABLE "poll_invites" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "poll_id" BIGINT,
  "department_member_id" BIGINT,
  "invited_at" TIMESTAMP,
  "vote_status" VARCHAR DEFAULT 'PENDING'
);

CREATE TABLE "votes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "poll_id" BIGINT,
  "option_id" BIGINT,
  "user_id" BIGINT,
  "created_at" TIMESTAMP
);

-- Indexes
CREATE INDEX "idx_user_email" ON "users" ("email");
CREATE UNIQUE INDEX ON "department_members" ("email", "department_id");
CREATE INDEX "idx_poll_creator" ON "polls" ("creator_id");
CREATE INDEX "idx_poll_active" ON "polls" ("active");
CREATE INDEX "idx_poll_expires_at" ON "polls" ("expires_at");
CREATE INDEX "idx_poll_created_at" ON "polls" ("created_at");
CREATE INDEX "idx_poll_option_poll" ON "poll_options" ("poll_id");
CREATE UNIQUE INDEX ON "votes" ("poll_id", "user_id");
CREATE INDEX "idx_vote_poll" ON "votes" ("poll_id");
CREATE INDEX "idx_vote_user" ON "votes" ("user_id");
CREATE INDEX "idx_vote_option" ON "votes" ("option_id");
CREATE INDEX "idx_vote_created_at" ON "votes" ("created_at");

-- Foreign Keys
ALTER TABLE "polls" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");
ALTER TABLE "poll_options" ADD FOREIGN KEY ("poll_id") REFERENCES "polls" ("id");
ALTER TABLE "poll_invites" ADD FOREIGN KEY ("poll_id") REFERENCES "polls" ("id");
ALTER TABLE "poll_invites" ADD FOREIGN KEY ("department_member_id") REFERENCES "department_members" ("id");
ALTER TABLE "votes" ADD FOREIGN KEY ("poll_id") REFERENCES "polls" ("id");
ALTER TABLE "votes" ADD FOREIGN KEY ("option_id") REFERENCES "poll_options" ("id");
ALTER TABLE "votes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "department_members" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id");
